"""PostgreSQL/Supabase implementation of the database interface."""

from __future__ import annotations

import logging
import re
from typing import Any

import psycopg
from psycopg.rows import dict_row

from .interface import DatabaseInterface
from .models import CLEAR_ORDER, CREATE_TABLES

logger = logging.getLogger(__name__)


def postgres_sql(query: str) -> str:
    """Translate the small SQLite SQL dialect used by the application."""
    translated = query
    translated = re.sub(
        r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        translated,
        flags=re.IGNORECASE,
    )
    translated = re.sub(
        r"datetime\s*\(\s*['\"]now['\"]\s*\)",
        "to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')",
        translated,
        flags=re.IGNORECASE,
    )
    translated = re.sub(
        r"\bINSERT\s+OR\s+IGNORE\s+INTO\b",
        "INSERT INTO",
        translated,
        flags=re.IGNORECASE,
    )
    translated = translated.replace("?", "%s")
    if re.search(r"\bINSERT\s+OR\s+IGNORE\b", query, re.IGNORECASE):
        translated = translated.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    return translated


class PostgresAdapter(DatabaseInterface):
    """Synchronous psycopg adapter for the self-hosted Supabase database."""

    schema_managed_externally = True

    def __init__(self, database_url: str):
        self.database_url = database_url
        self.conn: psycopg.Connection | None = None

    def connect(self) -> None:
        self.conn = psycopg.connect(
            self.database_url,
            row_factory=dict_row,
            connect_timeout=10,
            autocommit=True,
        )
        logger.info("Connected to Supabase PostgreSQL")

    def disconnect(self) -> None:
        if self.conn is not None:
            self.conn.close()
            self.conn = None

    def execute(self, query: str, params: tuple = ()) -> psycopg.Cursor:
        assert self.conn is not None, "Database not connected"
        with self.conn.transaction():
            cursor = self.conn.execute(postgres_sql(query), params)
        return cursor

    def insert_returning_id(self, query: str, params: tuple = ()) -> int:
        assert self.conn is not None, "Database not connected"
        sql = postgres_sql(query).rstrip().rstrip(";")
        if " returning " not in sql.lower():
            sql += " RETURNING id"
        with self.conn.transaction():
            row = self.conn.execute(sql, params).fetchone()
        if not row:
            raise RuntimeError("Insert did not generate an id")
        return int(row["id"])

    def executemany(self, query: str, params_list: list[tuple]) -> None:
        assert self.conn is not None, "Database not connected"
        with self.conn.transaction():
            self.conn.executemany(postgres_sql(query), params_list)

    def fetchall(self, query: str, params: tuple = ()) -> list[dict[str, Any]]:
        assert self.conn is not None, "Database not connected"
        rows = self.conn.execute(postgres_sql(query), params).fetchall()
        return [dict(row) for row in rows]

    def fetchone(self, query: str, params: tuple = ()) -> dict[str, Any] | None:
        assert self.conn is not None, "Database not connected"
        row = self.conn.execute(postgres_sql(query), params).fetchone()
        return dict(row) if row else None

    def create_tables(self) -> None:
        assert self.conn is not None, "Database not connected"
        required = {
            match.group(1)
            for statement in CREATE_TABLES
            if (
                match := re.search(
                    r"CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+(\w+)",
                    statement,
                    re.IGNORECASE,
                )
            )
        }
        existing = {
            row["table_name"]
            for row in self.conn.execute(
                "SELECT table_name FROM information_schema.tables "
                "WHERE table_schema = 'public'"
            ).fetchall()
        }
        missing = required - existing
        if missing:
            raise RuntimeError(
                "Supabase schema is incomplete; run the migration first. "
                f"Missing tables: {', '.join(sorted(missing))}"
            )
        logger.info("Supabase schema verified (%d application tables)", len(required))

    def clear_tables(self) -> None:
        assert self.conn is not None, "Database not connected"
        with self.conn.transaction():
            for table in CLEAR_ORDER:
                self.conn.execute(f'TRUNCATE TABLE "{table}" RESTART IDENTITY CASCADE')
