#!/usr/bin/env python3
"""Migrate the complete OrganAIzer SQLite database to Supabase PostgreSQL.

The source is never modified. The command exits non-zero unless every table,
row count and canonical row checksum is identical after migration.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sqlite3
from pathlib import Path
from typing import Any

import psycopg
from psycopg import sql
from psycopg.rows import dict_row

from backend.db.postgres_adapter import PostgresAdapter, postgres_sql


TASK_HISTORY_SQL = """
CREATE TABLE IF NOT EXISTS task_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    name TEXT NOT NULL,
    date TEXT NOT NULL DEFAULT
        (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')),
    status TEXT NOT NULL,
    result TEXT
)
"""

MIGRATION_ORDER = [
    "bereiche",
    "usergruppen",
    "intervalle",
    "termine",
    "termin_teilnehmer",
    "terminliste",
    "sip_config",
    "calls",
    "call_dialog_entries",
    "personen",
    "rollen",
    "person_rollen",
    "raeume",
    "komponenten",
    "planungsregeln",
    "planungsauftraege",
    "planungsauftrag_regeln",
    "ki_verbindungen",
    "verbindungen",
    "planungsregel_abhaengigkeiten",
    "zugangsanfragen",
    "n8n_config",
    "task_history",
]


def canonical_hash(rows: list[dict[str, Any]]) -> str:
    encoded = [
        json.dumps(row, sort_keys=True, ensure_ascii=False, default=str, separators=(",", ":"))
        for row in rows
    ]
    encoded.sort()
    return hashlib.sha256(("\n".join(encoded)).encode("utf-8")).hexdigest()


def sqlite_tables(conn: sqlite3.Connection) -> list[str]:
    rows = conn.execute(
        "SELECT name FROM sqlite_master "
        "WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
    )
    return [row[0] for row in rows]


def sqlite_rows(conn: sqlite3.Connection, table: str) -> list[dict[str, Any]]:
    return [dict(row) for row in conn.execute(f'SELECT * FROM "{table}"')]


def postgres_rows(conn: psycopg.Connection, table: str) -> list[dict[str, Any]]:
    return [
        dict(row)
        for row in conn.execute(
            sql.SQL("SELECT * FROM {}").format(sql.Identifier(table))
        ).fetchall()
    ]


def migrate(
    sqlite_path: Path,
    database_url: str,
    replace: bool,
    verify_only: bool = False,
) -> None:
    if not sqlite_path.is_file():
        raise SystemExit(f"SQLite source not found: {sqlite_path}")

    source = sqlite3.connect(f"file:{sqlite_path}?mode=ro", uri=True)
    source.row_factory = sqlite3.Row
    discovered = sqlite_tables(source)
    tables = [table for table in MIGRATION_ORDER if table in discovered]
    tables.extend(table for table in discovered if table not in tables)

    adapter = PostgresAdapter(database_url)
    adapter.connect()
    try:
        adapter.create_tables()
        adapter.execute(TASK_HISTORY_SQL)
    finally:
        adapter.disconnect()

    # Autocommit keeps metadata reads outside the migration transaction. The
    # explicit transaction below is therefore a real top-level COMMIT, not a
    # savepoint inside an implicit transaction that would roll back on close.
    target = psycopg.connect(database_url, row_factory=dict_row, autocommit=True)
    try:
        existing_counts = {
            table: target.execute(
                sql.SQL("SELECT count(*) AS count FROM {}").format(sql.Identifier(table))
            ).fetchone()["count"]
            for table in tables
        }
        if any(existing_counts.values()) and not replace and not verify_only:
            populated = {k: v for k, v in existing_counts.items() if v}
            raise SystemExit(
                "Target is not empty; refusing to overwrite. "
                f"Use --replace for this Supabase target: {populated}"
            )

        if not verify_only:
            with target.transaction():
                if replace:
                    for table in reversed(tables):
                        target.execute(
                            sql.SQL("TRUNCATE TABLE {} RESTART IDENTITY CASCADE").format(
                                sql.Identifier(table)
                            )
                        )

                for table in tables:
                    rows = sqlite_rows(source, table)
                    if not rows:
                        continue
                    columns = list(rows[0].keys())
                    statement = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
                        sql.Identifier(table),
                        sql.SQL(", ").join(map(sql.Identifier, columns)),
                        sql.SQL(", ").join(sql.Placeholder() for _ in columns),
                    )
                    with target.cursor() as cursor:
                        cursor.executemany(
                            statement,
                            [tuple(row[column] for column in columns) for row in rows],
                        )

                identity_rows = target.execute(
                    """
                    SELECT table_name, column_name
                    FROM information_schema.columns
                    WHERE table_schema='public' AND is_identity='YES'
                    """
                ).fetchall()
                for identity in identity_rows:
                    table = identity["table_name"]
                    column = identity["column_name"]
                    maximum = target.execute(
                        sql.SQL("SELECT COALESCE(MAX({}), 0) AS maximum FROM {}").format(
                            sql.Identifier(column), sql.Identifier(table)
                        )
                    ).fetchone()["maximum"]
                    sequence = target.execute(
                        "SELECT pg_get_serial_sequence(%s, %s) AS sequence",
                        (f"public.{table}", column),
                    ).fetchone()["sequence"]
                    if sequence:
                        target.execute(
                            "SELECT setval(%s, %s, %s)",
                            (sequence, max(maximum, 1), maximum > 0),
                        )

        # Verify through a fresh connection: this proves that the transaction
        # was committed and not merely visible to the importing session.
        target.close()
        target = psycopg.connect(database_url, row_factory=dict_row, autocommit=True)
        failures: list[str] = []
        total = 0
        print("TABLE\tSQLITE\tSUPABASE\tCHECKSUM")
        for table in tables:
            source_rows = sqlite_rows(source, table)
            target_rows = postgres_rows(target, table)
            source_hash = canonical_hash(source_rows)
            target_hash = canonical_hash(target_rows)
            ok = len(source_rows) == len(target_rows) and source_hash == target_hash
            total += len(source_rows)
            print(
                f"{table}\t{len(source_rows)}\t{len(target_rows)}\t"
                f"{'OK' if ok else 'MISMATCH'} {target_hash}"
            )
            if not ok:
                failures.append(table)
        if failures:
            raise SystemExit(f"Verification failed for: {', '.join(failures)}")
        print(f"VERIFIED\t{len(tables)} tables\t{total} rows\tALL DATA IDENTICAL")
    finally:
        target.close()
        source.close()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sqlite", required=True, type=Path)
    parser.add_argument("--database-url", required=True)
    parser.add_argument("--replace", action="store_true")
    parser.add_argument("--verify-only", action="store_true")
    args = parser.parse_args()
    migrate(args.sqlite, args.database_url, args.replace, args.verify_only)


if __name__ == "__main__":
    main()
